title: Sydney DeMets
description: PhD Candidate. Wesbite lovingly ripped off from Sebastian Kimberk.
url: https://sydneydemets.github.io

permalink: /blog/:title

theme: minima


plugins:
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll-sitemap
